### ISSUE TITLE
Recompiling two files issues

### ISSUE THREAD

**Issue by qingwh** [Raymw/Federated-XGBoost#4]
Hi,
I followed these steps:
1. I downloaded XGBoost package version 1.1.0 and a full build of the package.
I used git clone --recursive https://github.com/dmlc/xgboost
cd xgboost
mkdir build
cd build
cmake ..
make -j$(nproc) to build the package.
2. I modified the two files-"param.h"and "updater_histmaker.cc" of XGBoost, and recompiled. I got an error.

I used cd build
cmake ..
make -j$(nproc) to recompile files

![image](https://user-images.githubusercontent.com/42252673/81965699-6fdd1d00-95e6-11ea-974d-3ce4c4168d5d.png)

Many thanks!

**Comment by Raymw** [comment]
hi
you may change the version of XGBoost to 0.9 and modify those two files and recompile it. It should work under that version.
Thanks !

**Comment by qingwh** [comment]
Thanks for your help. I am going to use version 0.9.
